# Ejercicio 1 

### Carga el dataset y explora su estructura
### Lee el CSV, revisa dimensiones, tipos de datos y primeras filas
### Pregunta: ¿Cuántas filas tiene el dataset? ¿Qué columnas hay? ¿Qué tipo de dato es la fecha?

In [3]:
import pandas as pd

df = pd.read_csv('data/AEP_hourly.csv')

In [4]:
df.head()

              Datetime   AEP_MW
0  2004-12-31 01:00:00  13478.0
1  2004-12-31 02:00:00  12865.0
2  2004-12-31 03:00:00  12577.0
3  2004-12-31 04:00:00  12517.0
4  2004-12-31 05:00:00  12670.0

In [5]:
print(df.shape) #df.shape: Permite conocer el tamaño de un df
print(df.shape[0]) #Cantidad de filas
print(df.shape[1]) #Cantidad de columnas

(121273, 2)
121273
2

In [6]:
print(df.dtypes) #dtypes: permite conocer el tipo de dato de cada columna

Datetime        str
AEP_MW      float64
dtype: object

In [7]:
print(df.head(5))

              Datetime   AEP_MW
0  2004-12-31 01:00:00  13478.0
1  2004-12-31 02:00:00  12865.0
2  2004-12-31 03:00:00  12577.0
3  2004-12-31 04:00:00  12517.0
4  2004-12-31 05:00:00  12670.0

In [8]:
print(df.tail(10))

                   Datetime   AEP_MW
121263  2018-01-01 15:00:00  18619.0
121264  2018-01-01 16:00:00  18691.0
121265  2018-01-01 17:00:00  19109.0
121266  2018-01-01 18:00:00  20279.0
121267  2018-01-01 19:00:00  20925.0
121268  2018-01-01 20:00:00  21089.0
121269  2018-01-01 21:00:00  20999.0
121270  2018-01-01 22:00:00  20820.0
121271  2018-01-01 23:00:00  20415.0
121272  2018-01-02 00:00:00  19993.0

# Ejercicio 2

### Convierte la columna de fecha a datetime
### La fecha viene como texto — necesitas convertirla para poder operar con ella
### Como ingeniero: esto es como convertir unidades. El dato existe pero en formato inútil hasta que lo transformas.

In [9]:
df['Datetime'] = pd.to_datetime(df['Datetime']) #Convierte el valor a data time

In [10]:
print(df.dtypes)

Datetime    datetime64[us]
AEP_MW             float64
dtype: object

In [11]:
# Se usan para agrupar/extraer fechas 

df['Year'] = df['Datetime'].dt.year
df['Month'] = df['Datetime'].dt.month
df['Hour'] = df['Datetime'].dt.hour

In [12]:
print(df[['Datetime', 'Year', 'Month', 'Hour']].head())

             Datetime  Year  Month  Hour
0 2004-12-31 01:00:00  2004     12     1
1 2004-12-31 02:00:00  2004     12     2
2 2004-12-31 03:00:00  2004     12     3
3 2004-12-31 04:00:00  2004     12     4
4 2004-12-31 05:00:00  2004     12     5

# Ejercicio 3

## Calcula media, mínimo, máximo y desviación estándar del consumo energético
## Pregunta: ¿Qué tan variable es el consumo? Compara la desviación estándar con la media — ese ratio te dice mucho.

In [13]:
df

                  Datetime   AEP_MW  Year  Month  Hour
0      2004-12-31 01:00:00  13478.0  2004     12     1
1      2004-12-31 02:00:00  12865.0  2004     12     2
2      2004-12-31 03:00:00  12577.0  2004     12     3
3      2004-12-31 04:00:00  12517.0  2004     12     4
4      2004-12-31 05:00:00  12670.0  2004     12     5
...                    ...      ...   ...    ...   ...
121268 2018-01-01 20:00:00  21089.0  2018      1    20
121269 2018-01-01 21:00:00  20999.0  2018      1    21
121270 2018-01-01 22:00:00  20820.0  2018      1    22
121271 2018-01-01 23:00:00  20415.0  2018      1    23
121272 2018-01-02 00:00:00  19993.0  2018      1     0

[121273 rows x 5 columns]

In [14]:
print(df['AEP_MW'].describe()) #Da una descripcion estadistica de la columna seleccionada

count    121273.000000
mean      15499.513717
std        2591.399065
min        9581.000000
25%       13630.000000
50%       15310.000000
75%       17200.000000
max       25695.000000
Name: AEP_MW, dtype: float64

In [15]:
print(f"Media: {df['AEP_MW'].mean():.1f} MW") #Muestra la media ademas :.#f se usa para indicar la cantidad de decimales

Media: 15499.5 MW

In [16]:
print(f"Maximo: {df['AEP_MW'].max():.1f} MW") #Muestra el maximo

Maximo: 25695.0 MW

In [17]:
print(f"Minimo: {df["AEP_MW"].min():.1f} MW") #Muestra el minimo

Minimo: 9581.0 MW

In [18]:
print(f"Desv. std {df['AEP_MW'].std():.1f} MW") #Muestra la desviacion estandar

Desv. std 2591.4 MW

In [19]:
std = df['AEP_MW'].std()
media = df['AEP_MW'].mean()
CV = (std/media)*100
print(f"Porcentaje de desviación: {CV:.1f} %") #Muestra el porcentaje de variacion

Porcentaje de desviación: 16.7 %

# Ejercicio 4
## Consumo promedio por hora del día
## ¿A qué hora se consume más energía? Agrupa por hora y calcula el promedio

In [20]:
consumo_por_hora = df.groupby('Hour')['AEP_MW'].mean().round(1) # agrupa por horas los datos de los dias del df y les calcula la media
print(consumo_por_hora)

Hour
0     14651.2
1     13891.5
2     13432.1
3     13184.0
4     13095.2
5     13240.5
6     13802.4
7     14781.7
8     15478.8
9     15822.7
10    16084.3
11    16306.3
12    16398.2
13    16477.8
14    16534.7
15    16492.8
16    16444.5
17    16542.0
18    16762.9
19    16868.7
20    16821.3
21    16763.8
22    16469.0
23    15632.6
Name: AEP_MW, dtype: float64

In [21]:
print(consumo_por_hora.sort_values(ascending=False).head()) # organiza los datos de forma descendente y muestra los primeros 5

Hour
19    16868.7
20    16821.3
21    16763.8
18    16762.9
17    16542.0
Name: AEP_MW, dtype: float64

In [22]:
hora_pico = consumo_por_hora.idxmax() # muestra el indice en donde esta ubicado el mayor valor

print(f"Hora de mayor consumo: {hora_pico}:00 hrs")

Hora de mayor consumo: 19:00 hrs

In [23]:
df

                  Datetime   AEP_MW  Year  Month  Hour
0      2004-12-31 01:00:00  13478.0  2004     12     1
1      2004-12-31 02:00:00  12865.0  2004     12     2
2      2004-12-31 03:00:00  12577.0  2004     12     3
3      2004-12-31 04:00:00  12517.0  2004     12     4
4      2004-12-31 05:00:00  12670.0  2004     12     5
...                    ...      ...   ...    ...   ...
121268 2018-01-01 20:00:00  21089.0  2018      1    20
121269 2018-01-01 21:00:00  20999.0  2018      1    21
121270 2018-01-01 22:00:00  20820.0  2018      1    22
121271 2018-01-01 23:00:00  20415.0  2018      1    23
121272 2018-01-02 00:00:00  19993.0  2018      1     0

[121273 rows x 5 columns]

# Ejercicio 5
## Consumo promedio por mes — estacionalidad
## Identifica qué meses tienen mayor demanda energética y por qué
## Como termodinámico: verás dos picos (verano e invierno) por HVAC. El valle en primavera/otoño es cuando la carga térmica es mínima.

In [24]:
consumo_mes = df.groupby('Month') ['AEP_MW'].mean()

meses = ['Ene', 'Feb', 'Mar','Abr' ,'May', 'Jun', 'Jul', 'Ago', 'Sep', 'Oct', 'Nov', 'Dic']
consumo_mes.index = meses

print(consumo_mes)

Ene    17431.269009
Feb    17022.815084
Mar    15376.835720
Abr    13823.857511
May    14006.393817
Jun    15630.021825
Jul    16349.853303
Ago    16424.881699
Sep    14657.280556
Oct    13938.926431
Nov    14930.405676
Dic    16445.609084
Name: AEP_MW, dtype: float64

In [27]:
print(f"\nMes más alto: {consumo_mes.idxmax()}")
print(f"\nMes más bajo: {consumo_mes.idxmin()}")

Mes más alto: Ene

Mes más bajo: Abr

# Ejercicio 6

## Filtra solo los años completos
## Elimina años con datos incompletos para no sesgar el análisis
## Un año completo tiene 8,760 horas. Si un año tiene menos, los datos están incompletos y pueden distorsionar promedios anuales.

In [28]:
registros_por_año = df.groupby('Year')['AEP_MW'].count()
print(registros_por_año)

Year
2004    2206
2005    8758
2006    8758
2007    8758
2008    8782
2009    8758
2010    8757
2011    8758
2012    8781
2013    8758
2014    8759
2015    8760
2016    8784
2017    8760
2018    5136
Name: AEP_MW, dtype: int64

In [29]:
años_completos = registros_por_año[registros_por_año>8000].index
df_clean = df[df['Year'].isin(años_completos)]

In [31]:
print(f"\nRegistros originales: {len(df)}")
print(f"\nRegistros limpios: {len(df_clean)}")
df_clean

Registros originales: 121273

Registros limpios: 113931

                  Datetime   AEP_MW  Year  Month  Hour
23     2005-01-01 00:00:00  12892.0  2005      1     0
2207   2005-12-31 01:00:00  14254.0  2005     12     1
2208   2005-12-31 02:00:00  13761.0  2005     12     2
2209   2005-12-31 03:00:00  13445.0  2005     12     3
2210   2005-12-31 04:00:00  13306.0  2005     12     4
...                    ...      ...   ...    ...   ...
116133 2017-01-01 20:00:00  13962.0  2017      1    20
116134 2017-01-01 21:00:00  13770.0  2017      1    21
116135 2017-01-01 22:00:00  13508.0  2017      1    22
116136 2017-01-01 23:00:00  13102.0  2017      1    23
116137 2017-01-02 00:00:00  12618.0  2017      1     0

[113931 rows x 5 columns]

In [32]:
registros_eliminados = len(df)-len(df_clean)
print(registros_eliminados)

7342

In [33]:
años_eliminados = registros_por_año[registros_por_año <= 8000]
print(años_eliminados)

Year
2004    2206
2018    5136
Name: AEP_MW, dtype: int64