# Ejercicio 1 

### Carga el dataset y explora su estructura
### Lee el CSV, revisa dimensiones, tipos de datos y primeras filas
### Pregunta: ¿Cuántas filas tiene el dataset? ¿Qué columnas hay? ¿Qué tipo de dato es la fecha?

In [65]:
import pandas as pd

df = pd.read_csv('data/AEP_hourly.csv')

In [66]:
df.head()

              Datetime   AEP_MW
0  2004-12-31 01:00:00  13478.0
1  2004-12-31 02:00:00  12865.0
2  2004-12-31 03:00:00  12577.0
3  2004-12-31 04:00:00  12517.0
4  2004-12-31 05:00:00  12670.0

In [67]:
print(df.shape) #df.shape: Permite conocer el tamaño de un df
print(df.shape[0]) #Cantidad de filas
print(df.shape[1]) #Cantidad de columnas

(121273, 2)
121273
2

In [68]:
print(df.dtypes) #dtypes: permite conocer el tipo de dato de cada columna

Datetime        str
AEP_MW      float64
dtype: object

In [69]:
print(df.head(5))

              Datetime   AEP_MW
0  2004-12-31 01:00:00  13478.0
1  2004-12-31 02:00:00  12865.0
2  2004-12-31 03:00:00  12577.0
3  2004-12-31 04:00:00  12517.0
4  2004-12-31 05:00:00  12670.0

In [70]:
print(df.tail(10))

                   Datetime   AEP_MW
121263  2018-01-01 15:00:00  18619.0
121264  2018-01-01 16:00:00  18691.0
121265  2018-01-01 17:00:00  19109.0
121266  2018-01-01 18:00:00  20279.0
121267  2018-01-01 19:00:00  20925.0
121268  2018-01-01 20:00:00  21089.0
121269  2018-01-01 21:00:00  20999.0
121270  2018-01-01 22:00:00  20820.0
121271  2018-01-01 23:00:00  20415.0
121272  2018-01-02 00:00:00  19993.0

# Ejercicio 2

### Convierte la columna de fecha a datetime
### La fecha viene como texto — necesitas convertirla para poder operar con ella
### Como ingeniero: esto es como convertir unidades. El dato existe pero en formato inútil hasta que lo transformas.

In [53]:
df['Datetime'] = pd.to_datetime(df['Datetime']) #Convierte el valor a data time

In [54]:
df

                  Datetime   AEP_MW  Year  Month  Hour
0      2004-12-31 01:00:00  13478.0  2004     12     1
1      2004-12-31 02:00:00  12865.0  2004     12     2
2      2004-12-31 03:00:00  12577.0  2004     12     3
3      2004-12-31 04:00:00  12517.0  2004     12     4
4      2004-12-31 05:00:00  12670.0  2004     12     5
...                    ...      ...   ...    ...   ...
121268 2018-01-01 20:00:00  21089.0  2018      1    20
121269 2018-01-01 21:00:00  20999.0  2018      1    21
121270 2018-01-01 22:00:00  20820.0  2018      1    22
121271 2018-01-01 23:00:00  20415.0  2018      1    23
121272 2018-01-02 00:00:00  19993.0  2018      1     0

[121273 rows x 5 columns]

In [55]:
print(df.shape)
print(df.dtypes)

(121273, 5)
Datetime    datetime64[us]
AEP_MW             float64
Year                 int32
Month                int32
Hour                 int32
dtype: object

In [56]:
# Se usan para agrupar/extraer fechas 

df['Year'] = df['Datetime'].dt.year
df['Month'] = df['Datetime'].dt.month
df['Hour'] = df['Datetime'].dt.hour

In [57]:
df

                  Datetime   AEP_MW  Year  Month  Hour
0      2004-12-31 01:00:00  13478.0  2004     12     1
1      2004-12-31 02:00:00  12865.0  2004     12     2
2      2004-12-31 03:00:00  12577.0  2004     12     3
3      2004-12-31 04:00:00  12517.0  2004     12     4
4      2004-12-31 05:00:00  12670.0  2004     12     5
...                    ...      ...   ...    ...   ...
121268 2018-01-01 20:00:00  21089.0  2018      1    20
121269 2018-01-01 21:00:00  20999.0  2018      1    21
121270 2018-01-01 22:00:00  20820.0  2018      1    22
121271 2018-01-01 23:00:00  20415.0  2018      1    23
121272 2018-01-02 00:00:00  19993.0  2018      1     0

[121273 rows x 5 columns]

In [58]:
print(df[['Datetime', 'Year', 'Month', 'Hour']].head())

             Datetime  Year  Month  Hour
0 2004-12-31 01:00:00  2004     12     1
1 2004-12-31 02:00:00  2004     12     2
2 2004-12-31 03:00:00  2004     12     3
3 2004-12-31 04:00:00  2004     12     4
4 2004-12-31 05:00:00  2004     12     5